import { test, expect } from '@playwright/test';

test('private feedback, draft, publish, refresh, conflict and withdrawal preserve locations', async ({page, context, request}) => {
  test.setTimeout(120000);
  const catalog = await (await request.get('/data/photos.geojson')).json();
  const feature = catalog.features.find(f => f.properties.places?.length && f.properties.id !== 'E08DA55F7B0411E4A348406186009F3A');
  const xid = feature.properties.id;
  const replacement = catalog.features.flatMap(f => f.properties.places || []).find(p => !feature.properties.places.some(old => old.id === p.id));
  const before = await (await request.get('/api/review-state?snapshot=1')).json();
  expect((await request.post('/api/feedback', {data:{submission_id:crypto.randomUUID(),xid,message:'Soukromá testovací připomínka',email:'private@example.com'}})).status()).toBe(200);
  await page.goto(`/?xid=${xid}`);
  await expect(page.locator('#archive-modal')).toHaveClass(/is-open/);
  const admin = await context.newPage();
  await admin.goto('/admin.html');
  await admin.locator('#annotation-xid').fill(xid);
  await admin.locator('#annotation-load').click();
  await expect(admin.locator('#annotation-content')).toBeVisible();
  await expect(admin.locator('#annotation-text')).toHaveValue('');
  await admin.locator('#annotation-text').fill('Testovací kurátorské upřesnění <script>test</script>');
  await admin.locator('#annotation-evidence').fill('Soukromý důkaz private@example.com');
  await admin.locator('#annotation-mode').selectOption('replace');
  await admin.locator('#annotation-places').selectOption([replacement.id]);
  await admin.locator('#annotation-draft').click();
  await expect(admin.locator('#annotation-status')).toContainText('Rozpracované');
  expect((await (await request.get('/api/photo-annotations')).json()).items.some(a=>a.xid===xid)).toBe(false);
  await admin.locator('#annotation-publish').click();
  await expect(admin.locator('#annotation-status')).toContainText('je zveřejněné');
  await expect(page.locator('#photo-details')).toContainText('Testovací kurátorské upřesnění');
  expect(await page.locator('#photo-details script').count()).toBe(0);
  const snapshot = await (await request.get('/api/photo-annotations')).json();
  const item = snapshot.items.find(a=>a.xid===xid);
  expect(item.places[0].id).toBe(replacement.id);
  await expect(page.locator('#photo-details')).toHaveAttribute('data-metadata-revision', String(snapshot.metadata_revision));
  await expect(page.locator('#map-search')).toHaveAttribute('data-metadata-revision', String(snapshot.metadata_revision));
  expect(JSON.stringify(snapshot)).not.toContain('private@example.com');
  expect((await request.post('/api/admin/photo-annotations',{data:{xid,expected_revision:1,action:'withdraw'}})).status()).toBe(409);
  const fresh = await context.newPage();
  await fresh.goto(`/?xid=${xid}&search=place&search_id=${encodeURIComponent(replacement.id)}`);
  await expect(fresh.locator('#photo-details')).toContainText('Testovací kurátorské upřesnění');
  await expect(fresh.locator('#search-filter')).toContainText(replacement.label);
  await fresh.locator('#archive-modal button[data-modal-close]').click();
  await fresh.locator('#map-search').fill(replacement.label);
  await expect(fresh.locator('[role=option][data-kind=place]').filter({hasText:replacement.label}).first()).toBeVisible();
  await fresh.locator('#map-search').fill('Testovací kurátorské');
  await expect(fresh.locator('[role=option][data-kind=description]').filter({hasText:'Testovací kurátorské'})).toBeVisible();
  await admin.locator('#annotation-withdraw').click();
  await expect(admin.locator('#annotation-status')).toContainText('je stažené');
  await expect(page.locator('#photo-details')).not.toContainText('Testovací kurátorské upřesnění');
  const after = await (await request.get('/api/review-state?snapshot=1')).json();
  expect(after.groupCorrections).toEqual(before.groupCorrections);
  expect(after.revision).toBe(before.revision);
  expect(feature.geometry).toEqual(catalog.features.find(f=>f.properties.id===xid).geometry);
  await fresh.close(); await admin.close();
});

test('published annotation stays with its XID when a curator changes the group', async ({page, request}) => {
  const catalog = await (await request.get('/data/photos.geojson')).json();
  const feature = catalog.features[10];
  const target = catalog.features.find(f=>f.properties.group_id!==feature.properties.group_id);
  const xid = feature.properties.id;
  const body = {xid,expected_revision:0,action:'publish',public_text:'Testovací upřesnění stálého XID',evidence_note:'Lokální test',place_mode:'unknown',place_ids:[],disputed_place_ids:[]};
  expect((await request.post('/api/admin/photo-annotations',{data:body})).status()).toBe(200);
  const snapshot = await (await request.get('/api/photo-annotations')).json();
  expect((await request.post('/api/admin/group-membership',{data:{source_group_id:feature.properties.group_id,target_group_id:target.properties.group_id,xids:[xid],reason:'Lokální test stálého XID'}})).status()).toBe(200);
  expect(await (await request.get('/api/photo-annotations')).json()).toEqual(snapshot);
  await page.goto(`/?xid=${xid}`);
  await expect(page.locator('#photo-details')).toContainText(body.public_text);
  await expect(page.locator('#photo-details')).toContainText('Správce místo zatím neurčil.');
  expect((await request.post('/api/admin/group-membership',{data:{source_group_id:target.properties.group_id,target_group_id:feature.properties.group_id,xids:[xid],reason:'Vrácení lokální testovací změny'}})).status()).toBe(200);
  expect((await request.post('/api/admin/photo-annotations',{data:{xid,expected_revision:1,action:'withdraw'}})).status()).toBe(200);
});

test('failed A to B load locks writes and retains an explicitly restorable draft', async ({page}) => {
  const writes=[];
  let failB=true;
  const photos=[{properties:{id:'review-A',description:'Archiv A',places:[]}},{properties:{id:'review-B',description:'Archiv B',places:[]}}];
  await page.route('**/data/photos.geojson',route=>route.fulfill({json:{features:photos}}));
  await page.route('**/api/admin/photo-annotations**',route=>{
    if(route.request().method()==='POST') {
      writes.push(route.request().postDataJSON());
      return route.fulfill({json:{ok:true,revision:1}});
    }
    const xid=new URL(route.request().url()).searchParams.get('xid');
    if(xid==='review-B' && failB) return route.fulfill({status:503,json:{detail:'Načtení B selhalo'}});
    return route.fulfill({json:{photo:photos.find(p=>p.properties.id===xid).properties,annotation:null,history:[]}});
  });
  await page.goto('/admin.html');
  await page.locator('#annotation-xid').fill('review-A');
  await page.locator('#annotation-load').click();
  await expect(page.locator('#annotation-loaded')).toHaveText('Načtená fotografie: review-A');
  await page.locator('#annotation-text').fill('Rozepsané vysvětlení A');
  await page.locator('#annotation-xid').fill('review-B');
  for(const name of ['draft','publish','withdraw']) await expect(page.locator(`#annotation-${name}`)).toBeDisabled();
  await page.locator('#annotation-load').click();
  await expect(page.locator('#annotation-status')).toHaveText('Načtení B selhalo');
  await expect(page.locator('#annotation-content')).toBeHidden();
  for(const name of ['draft','publish','withdraw']) await expect(page.locator(`#annotation-${name}`)).toBeDisabled();
  // A programmatically dispatched stale click must also fail the action guard.
  await page.locator('#annotation-publish').dispatchEvent('click');
  await page.locator('#annotation-withdraw').dispatchEvent('click');
  expect(writes).toEqual([]);
  await page.locator('#annotation-xid').fill('review-A');
  await page.locator('#annotation-load').click();
  await expect(page.locator('#annotation-restore')).toBeVisible();
  await page.locator('#annotation-restore').click();
  await expect(page.locator('#annotation-text')).toHaveValue('Rozepsané vysvětlení A');
  failB=false;
  await page.locator('#annotation-xid').fill('review-B');
  await page.locator('#annotation-load').click();
  await expect(page.locator('#annotation-loaded')).toHaveText('Načtená fotografie: review-B');
  await expect(page.locator('#annotation-text')).toHaveValue('');
  await page.locator('#annotation-text').fill('Ověřené vysvětlení B');
  await page.locator('#annotation-evidence').fill('Doklad B');
  await page.locator('#annotation-publish').click();
  await expect.poll(()=>writes.length).toBe(1);
  expect(writes[0].xid).toBe('review-B');
  expect(writes[0].expected_revision).toBe(0);
});

test('place catalog failure commits no partial loaded record', async ({page}) => {
  let fail=true;
  await page.route('**/api/admin/photo-annotations**',route=>route.fulfill({json:{photo:{id:'review-C',description:'Archiv C',places:[]},annotation:null,history:[]}}));
  await page.route('**/data/photos.geojson',route=> fail ? route.fulfill({status:503}) : route.fulfill({json:{features:[]}}));
  await page.goto('/admin.html');
  await page.locator('#annotation-xid').fill('review-C');
  await page.locator('#annotation-load').click();
  await expect(page.locator('#annotation-status')).toContainText('Seznam míst se nepodařilo načíst');
  await expect(page.locator('#annotation-content')).toBeHidden();
  await expect(page.locator('#annotation-loaded')).toHaveText('');
  await expect(page.locator('#annotation-archive')).toHaveText('');
  await expect(page.locator('#annotation-publish')).toBeDisabled();
  fail=false;
  await page.locator('#annotation-load').click();
  await expect(page.locator('#annotation-loaded')).toHaveText('Načtená fotografie: review-C');
  await expect(page.locator('#annotation-publish')).toBeEnabled();
});
